### ISSUE TITLE
Your theme is listed on jekyll-themes.com

### ISSUE THREAD

**Issue by Redgadget** [sunbliss/photorama#11]
Your theme has been listed on [https://jekyll-themes.com/](https://jekyll-themes.com/).

**Comment by sunbliss** [comment]
Thank you Sharath! @Redgadget 
I appreciate it a lot.

**Comment by Redgadget** [comment]
You're welcome @sunbliss . How do you know my name by the way?

**Comment by sunbliss** [comment]
@Redgadget I had sent you an email titled "Jekyll related" on Febr8th concerning the cart function for images...

**Comment by Redgadget** [comment]
Oh yeah! I didn't recognize it was you. So did you find any solution?

**Comment by sunbliss** [comment]
@Redgadget It is still on my 'ToDo' list, it is a complex feature. For the moment I am working on implementing a google maps page in jekyll with custom styling, markers and clusters, linking to the relevant posts. It is an easier task. The Jekyll Maps gem is not convenient since it is not an official Jekyll plugin and it requires to build the site locally and push the compiled pages.
