### ISSUE TITLE
 it didn't work after changing the main-title content in index.html.

### ISSUE THREAD

**Issue by Harkas** [sunbliss/photorama#13]
Hi,Anna Prigkipaki !
    Thanks for buliding a super wonderful jekyll theme ,I like it very much and have maked some changes ! 
    But the web url of my blog didn't work if i changed the main-title content in index.html. 
    Here is my blog URL: https://harkas.github.io/newblog.
    Would you help to check this issue ?
    Thanks a lot !

**Comment by sunbliss** [comment]
Hi @Harkas 
I just checked your link but the webpage is not rendering as it should.
Only the html code is visible.
Can you direct me to the exact repo so I can find the issue?
I am not sure by the way what is the change you are trying to make.
Is it about the main logo at the top left of the navbar?
Thank you

**Comment by Harkas** [comment]
Hi，Anna Prigkipaki @sunbliss !
Thanks for the reply！now the webpage is normal !
I have tried the way  you show it on `README.md` like this:
```
To change the welcome content at the far left of the Home page go here: /index.html and fill the responding lines of the YAML with your desired text.
```
But after I changed “<strong>PHOT•O•RAMA</strong>”to my  desired text such as “<strong>Welcome to my world</strong>”,only the html code is visible ! 
That's the problem!

**Comment by sunbliss** [comment]
Firstly I strongly advise that you fork the latest release where I have fixed some issues concerning the safe loading of the scripts and the toggling of the burger icon at home page!
Secondly, you MUST DELETE master branch, otherwise, github will not render the correct files and in particular the ones coming from 'gh-pages branch'.
Do try the above and let me know if the problem is solved.
Thank you

**Comment by Harkas** [comment]
Hi，Anna Prigkipaki @sunbliss !
I just now try your soulution,and it works !
Thank you very much for your help !

**Comment by sunbliss** [comment]
You are welcome!
Enjoy the template.
