### ISSUE TITLE
custome domain, photorama

### ISSUE THREAD

**Issue by EichFlo** [sunbliss/photorama#7]
Hey, thank you for this wonderful theme.

I have already forked it and gotten eveything to work just fine. It really is a fantastic theme.

However, I've run into a problem. I tried setting up my own domain. I bought a domain at godaddy and then followed your instructions. Made the CNAME file and then started to edit the DNS settings. 

The problem arrises when I try to add the CNAME record. I can't make it point at yourusername.github.io/repositoryname, I always get an error trying to do that. I can only add yourusername.github.io. I also made the two A records pointing at 192.30.252.153 and 192.30.252.154. 

Some content does display when I got to my domain, it's just very bugged. If you want to have look, here is my page http://www.meins-flo.de/.

if you have any idea on how to fix this, I would be very grateful.

Greetings 
Florian

I'm sorry for any language mistakes, English is not my primary language

**Comment by sunbliss** [comment]
@EichFlo Hello, sorry for the late reply but I was on vacations and I wasn't able to assist you.

I am glad you liked the template. I see you managed to solve your issue.

Apparently, there had been some changes since Jekyll 3.0 was launched and I neglected to update the info in README file. 

I do not use godaddy, so I would be grateful if you shared the configurations you applied. 

This way I can help more the rest of the template's users who want to use their own domain.

Thank you.

Many greetings
Anna

**Comment by EichFlo** [comment]
Woops sorry, didnt look here for ages sine I figured it out. Here is what I did:

You will need the CNAME file of course, pointing to www.yourdomain.something

Most important thing was the GoDaddy settings. The site site seems to be offline atm so I can't acess it right now to write them down. I will update this at a later point.

It was essentially just the settings you find online for GoDaddy when you google it
